# Generated by Django 2.2.4 on 2021-02-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsApp', '0002_auto_20210219_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dojo',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='dojo',
            name='state',
            field=models.CharField(max_length=255),
        ),
    ]
